### ISSUE TITLE
Can not install winterjs on ubuntu 24.04

### ISSUE THREAD

**Issue by flip111** [wasmerio/winterjs#75]
```
» cargo install --git https://github.com/wasmerio/winterjs winterjs
    Updating git repository `https://github.com/wasmerio/winterjs`
  Installing winterjs v1.1.0 (https://github.com/wasmerio/winterjs#6cee3096)
    Updating git repository `https://github.com/wasix-org/h2.git`
    Updating git repository `https://github.com/wasix-org/hyper`
    Updating git repository `https://github.com/wasix-org/hyper-rustls.git`
    Updating git repository `https://github.com/wasix-org/libc.git`
    Updating git repository `https://github.com/wasix-org/mio.git`
    Updating git repository `https://github.com/wasix-org/rustls.git`
    Updating git repository `https://github.com/wasix-org/socket2.git`
    Updating git repository `https://github.com/wasix-org/tokio.git`
    Updating crates.io index
    Updating git repository `https://github.com/wasmerio/spiderfire.git`
    Updating git repository `https://github.com/wasmerio/mozjs.git`
    Updating git repository `https://github.com/wasix-org/static-web-server`
    Updating git repository `https://github.com/wasix-org/rustls-native-certs.git`
    Updating git repository `https://github.com/wasix-org/tokio-rustls.git`
    Updating git repository `https://github.com/wasix-org/ring.git`
    Updating git repository `https://github.com/wasix-org/sct.git`
    Updating git repository `https://github.com/wasix-org/webpki.git`
    Updating git repository `https://github.com/wasix-org/libc.git`
    Updating git repository `https://github.com/wasix-org/signal-hook.git`
    Updating git repository `https://github.com/wasix-org/webpki-roots.git`
   Compiling proc-macro2 v1.0.81
   Compiling unicode-ident v1.0.12
   Compiling libc v0.2.152 (https://github.com/wasix-org/libc.git?branch=v0.2.152#26f165f1)
   Compiling cfg-if v1.0.0
   Compiling version_check v0.9.4
   Compiling serde v1.0.198
   Compiling autocfg v1.2.0
   Compiling cc v1.0.95
   Compiling pin-project-lite v0.2.14
   Compiling itoa v1.0.11
   Compiling memchr v2.7.2
   Compiling regex-syntax v0.8.3
   Compiling once_cell v1.19.0
   Compiling lazy_static v1.4.0
   Compiling hashbrown v0.14.3
   Compiling typenum v1.17.0
   Compiling tracing-core v0.1.32
   Compiling futures-core v0.3.30
   Compiling generic-array v0.14.7
   Compiling num-traits v0.2.18
   Compiling tinyvec_macros v0.1.1
   Compiling tinyvec v1.6.0
   Compiling percent-encoding v2.3.1
   Compiling aho-corasick v1.1.3
   Compiling quote v1.0.36
   Compiling syn v2.0.60
   Compiling getrandom v0.2.14
   Compiling num_cpus v1.16.0
   Compiling form_urlencoded v1.2.1
   Compiling serde_json v1.0.116
   Compiling rand_core v0.6.4
   Compiling unicode-bidi v0.3.15
   Compiling unicode-normalization v0.1.23
   Compiling fnv v1.0.7
   Compiling siphasher v0.3.11
   Compiling rand v0.8.5
   Compiling ryu v1.0.17
   Compiling phf_shared v0.11.2
   Compiling unicode-width v0.1.11
   Compiling uuid v1.8.0
   Compiling radium v0.7.0
   Compiling idna v0.5.0
   Compiling subtle v2.5.0
   Compiling either v1.11.0
   Compiling regex-automata v0.4.6
   Compiling phf_generator v0.11.2
   Compiling slab v0.4.9
   Compiling data-encoding v2.5.0
   Compiling if_chain v1.0.2
   Compiling glob v0.3.1
   Compiling anyhow v1.0.82
   Compiling url v2.5.0
   Compiling tap v1.0.1
   Compiling stable_deref_trait v1.2.0
   Compiling outref v0.1.0
   Compiling rustc-hash v1.1.0
   Compiling futures-sink v0.3.30
   Compiling simd-abstraction v0.7.1
   Compiling wyz v0.5.1
   Compiling clang-sys v1.7.0
   Compiling num-bigint v0.4.4
   Compiling new_debug_unreachable v1.0.6
   Compiling rustix v0.38.34
   Compiling equivalent v1.0.1
   Compiling smallvec v1.13.2
   Compiling funty v2.0.0
   Compiling arc-swap v0.4.8
   Compiling bitflags v2.5.0
   Compiling indexmap v2.2.6
   Compiling base64-simd v0.7.0
   Compiling futures-channel v0.3.30
   Compiling signal-hook-registry v1.1.1 (https://github.com/wasix-org/signal-hook.git?branch=registry-v1.1.1#3de7855b)
   Compiling crypto-common v0.1.6
   Compiling block-buffer v0.10.4
   Compiling num-integer v0.1.46
   Compiling bitvec v1.0.1
   Compiling mio v0.8.9 (https://github.com/wasix-org/mio.git?branch=v0.8.9#f55de7d1)
   Compiling socket2 v0.5.5 (https://github.com/wasix-org/socket2.git?branch=v0.5.5#87e78d44)
   Compiling lock_api v0.4.11
   Compiling linux-raw-sys v0.4.13
   Compiling minimal-lexical v0.2.1
   Compiling unicode-id-start v1.1.2
   Compiling parking_lot_core v0.9.9
   Compiling thiserror v1.0.59
   Compiling regex v1.10.4
   Compiling scoped-tls v1.0.1
   Compiling futures-task v0.3.30
   Compiling pin-utils v0.1.0
   Compiling Inflector v0.11.4
   Compiling futures-io v0.3.30
   Compiling libloading v0.8.3
   Compiling better_scoped_tls v0.1.1
   Compiling nom v7.1.3
   Compiling digest v0.10.7
   Compiling swc_macros_common v0.3.10
   Compiling atty v0.2.14
   Compiling unicase v2.7.0
   Compiling home v0.5.9
   Compiling scopeguard v1.2.0
   Compiling rustversion v1.0.15
   Compiling termcolor v1.4.1
   Compiling bindgen v0.68.1
   Compiling log v0.4.21
   Compiling ring v0.17.7 (https://github.com/wasix-org/ring.git?branch=0.17.7#be27e9a6)
   Compiling lazycell v1.3.0
   Compiling pkg-config v0.3.30
   Compiling shlex v1.3.0
   Compiling peeking_take_while v0.1.2
   Compiling vcpkg v0.2.15
   Compiling psm v0.1.21
   Compiling which v4.4.2
   Compiling cexpr v0.6.0
   Compiling encoding_c v0.9.8
   Compiling cpufeatures v0.2.12
   Compiling encoding_c_mem v0.2.6
   Compiling same-file v1.0.6
   Compiling spin v0.9.8
   Compiling base64 v0.21.7
   Compiling walkdir v2.5.0
   Compiling stacker v0.1.15
   Compiling smartstring v1.0.1
   Compiling libz-sys v1.1.16
   Compiling ahash v0.8.11
   Compiling httparse v1.8.0
   Compiling camino v1.1.6
   Compiling unicode-id v0.3.4
   Compiling semver v1.0.22
   Compiling unicode-segmentation v1.11.0
   Compiling untrusted v0.9.0
   Compiling encoding_rs v0.8.34
   Compiling mime v0.3.17
   Compiling static_assertions v1.1.0
   Compiling typed-arena v2.0.2
   Compiling serde_derive v1.0.198
   Compiling tracing-attributes v0.1.27
   Compiling phf_macros v0.11.2
   Compiling futures-macro v0.3.30
   Compiling swc_visit_macros v0.5.11
   Compiling phf v0.11.2
   Compiling tokio-macros v2.2.0 (https://github.com/wasix-org/tokio.git?branch=wasix-1.35.1#833de725)
   Compiling futures-util v0.3.30
   Compiling ast_node v0.9.7
   Compiling tracing v0.1.40
   Compiling swc_eq_ignore_macros v0.1.3
   Compiling from_variant v0.1.7
   Compiling thiserror-impl v1.0.59
   Compiling string_enum v0.4.3
   Compiling swc_visit v0.5.13
   Compiling is-macro v0.3.5
   Compiling zerocopy v0.7.32
   Compiling syn v1.0.109
   Compiling mime_guess v2.0.4
   Compiling vergen v8.3.1
   Compiling dashmap v5.5.3
   Compiling try-lock v0.2.5
   Compiling byteorder v1.5.0
   Compiling httpdate v1.0.3
   Compiling rustls v0.22.2 (https://github.com/wasix-org/rustls.git?branch=v0.22.2#b1807952)
   Compiling rustls-pki-types v1.5.0
   Compiling want v0.3.1
   Compiling swc_config_macro v0.1.3
   Compiling proc-macro-error-attr v1.0.4
   Compiling zeroize v1.8.0
   Compiling tower-service v0.3.2
   Compiling ppv-lite86 v0.2.17
   Compiling prettyplease v0.2.19
   Compiling swc_ecma_transforms_macros v0.5.4
   Compiling rustls-pemfile v1.0.4
   Compiling rand_chacha v0.3.1
   Compiling sha-1 v0.10.0
   Compiling memoffset v0.9.1
   Compiling proc-macro-error v1.0.4
   Compiling iana-time-zone v0.1.60
   Compiling crc32fast v1.4.0
   Compiling alloc-no-stdlib v2.0.4
   Compiling alloc-stdlib v0.2.2
   Compiling chrono v0.4.38
   Compiling futures-executor v0.3.30
   Compiling cargo-platform v0.1.8
   Compiling mozjs_sys v0.68.2 (https://github.com/wasmerio/mozjs.git?branch=wasi-gecko#5e3485ec)
   Compiling bytes v1.6.0
   Compiling debugid v0.8.0
   Compiling triomphe v0.1.11
   Compiling swc_cached v0.3.20
   Compiling hstr v0.2.10
   Compiling mozjs v0.14.1 (https://github.com/wasmerio/mozjs.git?branch=wasi-gecko#5e3485ec)
error: failed to run custom build command for `mozjs_sys v0.68.2 (https://github.com/wasmerio/mozjs.git?branch=wasi-gecko#5e3485ec)`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installigoIts/release/build/mozjs_sys-d31ad2bf315ebc32/build-script-build` (exit status: 101)
  --- stdout
  cargo:outdir=/tmp/cargo-installigoIts/release/build/mozjs_sys-4c30476615520a6d/out/build
  [[ '/home/flip111/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/5e3485e/mozjs-sys'/mozjs/js/src/configure -ot '/home/flip111/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/5e3485e/mozjs-sys'/mozjs/js/src/configure.in ]] && touch '/home/flip111/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/5e3485e/mozjs-sys'/mozjs/js/src/configure || true
  [[ '/home/flip111/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/5e3485e/mozjs-sys'/mozjs/js/src/old-configure -ot '/home/flip111/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/5e3485e/mozjs-sys'/mozjs/js/src/old-configure.in ]] && touch '/home/flip111/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/5e3485e/mozjs-sys'/mozjs/js/src/old-configure || true
  ! [[ '/home/flip111/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/5e3485e/mozjs-sys'/mozjs/js/src/configure.in -ot '/home/flip111/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/5e3485e/mozjs-sys'/mozjs/js/src/configure ]] && touch '/home/flip111/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/5e3485e/mozjs-sys'/mozjs/js/src/configure || true
  ! [[ '/home/flip111/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/5e3485e/mozjs-sys'/mozjs/js/src/old-configure.in -ot '/home/flip111/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/5e3485e/mozjs-sys'/mozjs/js/src/old-configure ]] && touch '/home/flip111/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/5e3485e/mozjs-sys'/mozjs/js/src/old-configure || true
  if [[ '/home/flip111/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/5e3485e/mozjs-sys'/mozjs/js/src/configure -nt config.status ]] ; then \
    CC="cc" CFLAGS="" \
    CPP="cc -E" CPPFLAGS="-I/home/flip111/.cargo/registry/src/index.crates.io-6f17d22bba15001f/encoding_c_mem-0.2.6/include -I/usr/include " \
    CXX="c++" CXXFLAGS="" \
    AS="" AR="ar" \
    '/home/flip111/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/5e3485e/mozjs-sys'/mozjs/js/src/configure --disable-jemalloc --disable-js-shell --disable-tests --disable-export-js --disable-shared-js --build-backends=RecursiveMake --enable-js-streams || (cat config.log && exit 1) ; \
  fi

  --- stderr
  gmake: *** No targets specified and no makefile found.  Stop.
  Traceback (most recent call last):
    File "/home/flip111/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/5e3485e/mozjs-sys/mozjs/js/src/../../configure.py", line 35, in <module>
      from mozbuild.configure import TRACE, ConfigureSandbox
    File "/home/flip111/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/5e3485e/mozjs-sys/mozjs/python/mozbuild/mozbuild/configure/__init__.py", line 18, in <module>
      from six.moves import builtins as __builtin__
  ModuleNotFoundError: No module named 'six.moves'
  cat: config.log: No such file or directory
  make: *** [/home/flip111/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/5e3485e/mozjs-sys/makefile.cargo:158: maybe-configure] Error 1
  thread 'main' panicked at /home/flip111/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/5e3485e/mozjs-sys/build.rs:272:5:
  assertion failed: result.success()
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `winterjs v1.1.0 (https://github.com/wasmerio/winterjs#6cee3096)`, intermediate artifacts can be found at `/tmp/cargo-installigoIts`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

cargo 1.75.0 (1d8b05cdd 2023-11-20)
rustc 1.75.0 (82e1608df 2023-12-21)

**Comment by Arshia001** [comment]
This appears to be the same issue as #49.

Until that's fixed, you can simply remove usages of `six.moves`, as that is a python 2 -> python 3 compatibility layer and is not needed if you're already using python 3.

**Comment by flip111** [comment]
@Arshia001 in which places should the usages of `six.moves` be removed?

**Comment by Arshia001** [comment]
Wherever you're receiving errors, in this case it's `/home/flip111/.cargo/git/checkouts/mozjs-e1c76167ba7c548f/5e3485e/mozjs-sys/mozjs/python/mozbuild/mozbuild/configure/__init__.py` but there'll probably be more.
